### PR TITLE
chore: add comments to example manifest generated by `forc index new`

### PR DESCRIPTION
**Pull request by yash251**
solves #510

### CODE REVIEW

**Review by ra0x3 — CHANGES_REQUESTED** [review]
@yash251 
- Looks almost there!
- 2 things:

**1. Let's try to wrap comments at around a line length of maybe 70?**
So a line like this (1 long line):
```text
# The module field contains a file path that points to code that will be run as an executor inside of the indexer.
```
Would become (2 shorter lines):
```text
# The module field contains a file path that points to
# code that will be run as an executor inside of the indexer.
```
**2. Be mindful of indentation**

Your updated manifest content is indented, whereas the current manifest content is is not
   
Example:

What you have:
```rust
format!(
  r#"
      Your content is indented like this
  "#
);
```

What we want:
```rust
format!(
  r#"
It should not be indented, like this
  "#
);
```

Overall looks good. Changes should be easy to make 👌

**Comment by yash251** [comment]
> @yash251
> 
> * Looks almost there!
> * 2 things:
> 
> **1. Let's try to wrap comments at around a line length of maybe 70?** So a line like this (1 long line):
> 
> ```
> # The module field contains a file path that points to code that will be run as an executor inside of the indexer.
> ```
> 
> Would become (2 shorter lines):
> 
> ```
> # The module field contains a file path that points to
> # code that will be run as an executor inside of the indexer.
> ```
> 
> **2. Be mindful of indentation**
> 
> Your updated manifest content is indented, whereas the current manifest content is is not
> 
> Example:
> 
> What you have:
> 
> ```rust
> format!(
>   r#"
>       Your content is indented like this
>   "#
> );
> ```
> 
> What we want:
> 
> ```rust
> format!(
>   r#"
> It should not be indented, like this
>   "#
> );
> ```
> 
> Overall looks good. Changes should be easy to make 👌

For the first thing should I keep the note thing 
```
# Important: At this time, wasm is the preferred method of execution.
```
then it becomes 3 liner

**Comment by ra0x3** [comment]
@yash251

> then it becomes 3 liner

3 lines is fine :) we're more so concerned about it looking nice/neat without the long lines (rather than how many lines we have - if that makes sense).

**Comment by yash251** [comment]
> @yash251
> 
> > then it becomes 3 liner
> 
> 3 lines is fine :) we're more so concerned about it looking nice/neat without the long lines (rather than how many lines we have - if that makes sense).

alrightyyyy. so please check the requested changes

**Comment by yash251** [comment]
working ok

**Comment by deekerno** [comment]
@yash251 Go ahead and merge the latest changes from master, and then we'll test and review one more time. 😄

**Comment by yash251** [comment]
done

**Comment by yash251** [comment]
done

**Review by deekerno — APPROVED** [review]
Thanks for this!

**Review by ra0x3 — APPROVED** [review]
Thanks @yash251 looks great! 🥳

**Pull request merged**
