### PR TITLE
New sqlite support

### PR DESCRIPTION
**Pull request by tjsharp1**
Still need to get this merged with the new crate namings, but I've got the tests passing locally, so should be ready to start looking at.

### CODE REVIEW

**Comment by ra0x3** [comment]
@tjsharp1 
- Any specific test instructions for this? I can pull it down and try to test it while you're fixing conflicts. 
- Also, I can look through the code and get a decent idea of what's going on, but do you think you could add a short description of what this work does exactly? (In case I might be misunderstanding)

**Comment by ra0x3** [comment]
@tjsharp1 
- Other than those testing steps, anything else?
- When I pull down this branch I get the errors you alluded to [here](https://github.com/FuelLabs/fuel-indexer/pull/134/files#diff-45194c121f117b0405626e768b2f75f0f294fd0e6bffaab872f55d02ab00ece2R64) but in the postgres module, specifically the `root_columns_list_by_id`, `list_column_by_id`, and `columns_get_schema` methods.
- You already mentioned you were having the same issue just on the Sqlite side -- so I'm thinking this must not have been happening for you (on the Postgres side)? 🤔 
  - Project won't build in the mean time obviously

**Comment by JoshuaBatty** [comment]
Hi @tjsharp1 I just checked out your branch and followed your instructions. I'm getting a different error to you though. 

```
error[E0308]: mismatched types
   --> database/postgres/src/lib.rs:186:20
    |
186 | ... = sqlx::query_as!(NumVersions, "SELECT count(*) as num FROM graph_registry_type_ids WHERE schema_name = $1 AND schema_version = $2", name, version).fe...
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i64`, found enum `Option`
    |
    = note: expected type `i64`
               found enum `Option<i64>`
    = note: this error originates in the macro `$crate::sqlx_macros::expand_query` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by ra0x3** [comment]
@JoshuaBatty @tjsharp1 So funny enough, I was wrestling with this just now (cargo clean, fresh checkout, etc) -- with no luck. Then I just switched to the `rashad/126-add-e2e-docker-compose-test` and switched back (per TJ's comment).....and it worked 😆 wow 🤷

**Comment by ra0x3** [comment]
- Also, so I pulled this down to see if I could get anything working
- I can't even get the tests to run on my end -- getting errors such a

```bash
   Compiling fuel-indexer-sqlite v0.1.0 (/Users/rashad/Development/repos/fuel-indexer/database/sqlite)
error: unsupported type columntypename of column #5 ("column_type")
   --> database/postgres/src/lib.rs:217:5
    |
217 |     sqlx::query_as!(Columns, "SELECT id, type_id, column_position, column_name, column_type, nullable, graphql_type FROM graph_registry_columns WHERE type_id = $1", col_id).fe...
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in the macro `$crate::sqlx_macros::expand_query` (in Nightly builds, run with -Z macro-backtrace for more info)

error: unsupported type columntypename of column #5 ("column_type")
   --> database/postgres/src/lib.rs:225:5
    |
225 | /     sqlx::query_as!(
226 | |         ColumnInfo,
227 | |         r#"SELECT
228 | |                c.type_id as type_id,
...   |
240 | |         version
241 | |     )
    | |_____^
    |
    = note: this error originates in the macro `$crate::sqlx_macros::expand_query` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0308]: mismatched types
  --> database/postgres/src/lib.rs:69:5
   |
69 | /     sqlx::query_as!(
70 | |         RootColumns,
71 | |         r#"SELECT
72 | |                id, root_id, column_name, graphql_type
...  |
75 | |         root_id
76 | |     )
   | |_____^ expected `i64`, found `i32`
   |
   = note: this error originates in the macro `$crate::sqlx_macros::expand_query` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0308]: mismatched types
   --> database/postgres/src/lib.rs:217:5
    |
217 |     sqlx::query_as!(Columns, "SELECT id, type_id, column_position, column_name, column_type, nullable, graphql_type FROM graph_registry_columns WHERE type_id = $1", col_id).fe...
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i64`, found `i32`
    |
    = note: this error originates in the macro `$crate::sqlx_macros::expand_query` (in Nightly builds, run with -Z macro-backtrace for more info)
```

- So I tried just casting all the types to `::float` and to `::varchar` to just get _something_ going.
- That allowed the test suite to actually run, but then that failed with 

```bash
➜  fuel-indexer git:(217c15f) ✗ cargo test --all-features
    Finished test [unoptimized + debuginfo] target(s) in 0.75s
     Running unittests src/main.rs (target/debug/deps/counter_rs-f9c5784125f29cef)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/lib.rs (target/debug/deps/fuel_indexer-7dcd2678a9ffdd9d)

running 4 tests
test database::tests::test_schema_manager_sqlite ... FAILED
test executor::tests::test_sqlite ... FAILED
test database::tests::test_schema_manager_postgres ... FAILED
test executor::tests::test_postgres ... FAILED

failures:

---- database::tests::test_schema_manager_sqlite stdout ----
thread 'database::tests::test_schema_manager_sqlite' panicked at 'called `Result::unwrap()` on an `Err` value: ColumnDecode { index: "0", source: "mismatched types; Rust type `core::option::Option<f64>` (as SQL type `REAL`) is not compatible with SQL type `INTEGER`" }', /Users/rashad/.cargo/registry/src/github.com-1ecc6299db9ec823/sqlx-core-0.6.0/src/row.rs:73:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- executor::tests::test_sqlite stdout ----
thread 'executor::tests::test_sqlite' panicked at 'called `Result::unwrap()` on an `Err` value: ColumnDecode { index: "0", source: "mismatched types; Rust type `core::option::Option<f64>` (as SQL type `REAL`) is not compatible with SQL type `INTEGER`" }', /Users/rashad/.cargo/registry/src/github.com-1ecc6299db9ec823/sqlx-core-0.6.0/src/row.rs:73:37

---- database::tests::test_schema_manager_postgres stdout ----
thread 'database::tests::test_schema_manager_postgres' panicked at 'no entry found for key', fuel-indexer/src/database.rs:131:22

---- executor::tests::test_postgres stdout ----
thread 'tokio-runtime-worker' panicked at 'no entry found for key', fuel-indexer/src/database.rs:131:22
thread 'executor::tests::test_postgres' panicked at 'assertion failed: result.is_ok()', fuel-indexer/src/executor.rs:354:9


failures:
    database::tests::test_schema_manager_postgres
    database::tests::test_schema_manager_sqlite
    executor::tests::test_postgres
    executor::tests::test_sqlite

test result: FAILED. 0 passed; 4 failed; 0 ignored; 0 measured; 0 filtered out; finished in 7.44s
```

- And then once I saw the `is not compatible with SQL type `INTEGER`` I give up 🤷 
- With that said, I don't think this is a blocker to https://github.com/FuelLabs/fuel-indexer/issues/151 -- which is the next highest priority issue

**Comment by ra0x3** [comment]
@tjsharp1 
- So I just pulled this down and tried to test. Here's the error I'm seeing. 
- Sort've the same error I saw last time, but just limited to the type errors this time
- I tried `cargo clean` and switching branches, with no luck
- Since this passes on CI I think it gets a soft approval ✅ but would need to figure out what's causing these type errors before merging?
  - Thankfully I don't think this work is a blocker to https://github.com/FuelLabs/fuel-indexer/issues/151 as SwaySwap can work without sqlite, but can't work without #151
- I'm sure these errors are related some minor config/cache/something 

```bash
   Compiling sqlx v0.6.0
   Compiling fuel-indexer-postgres v0.1.0 (/Users/rashad/Development/repos/fuel-indexer/database/postgres)
   Compiling fuel-indexer-sqlite v0.1.0 (/Users/rashad/Development/repos/fuel-indexer/database/sqlite)
error: unsupported type columntypename of column #5 ("column_type")
   --> database/postgres/src/lib.rs:217:5
    |
217 |     sqlx::query_as!(Columns, "SELECT id, type_id, column_position, column_name, column_type, nullable, graphql_type FROM graph_registry_columns WHERE type_id = $1", col_id).fe...
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in the macro `$crate::sqlx_macros::expand_query` (in Nightly builds, run with -Z macro-backtrace for more info)

error: unsupported type columntypename of column #5 ("column_type")
   --> database/postgres/src/lib.rs:225:5
    |
225 | /     sqlx::query_as!(
226 | |         ColumnInfo,
227 | |         r#"SELECT
228 | |                c.type_id as type_id,
...   |
240 | |         version
241 | |     )
    | |_____^
    |
    = note: this error originates in the macro `$crate::sqlx_macros::expand_query` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0308]: mismatched types
  --> database/postgres/src/lib.rs:69:5
   |
69 | /     sqlx::query_as!(
70 | |         RootColumns,
71 | |         r#"SELECT
72 | |                id, root_id, column_name, graphql_type
...  |
75 | |         root_id
76 | |     )
   | |_____^ expected `i64`, found `i32`
   |
   = note: this error originates in the macro `$crate::sqlx_macros::expand_query` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0308]: mismatched types
   --> database/postgres/src/lib.rs:217:5
    |
217 |     sqlx::query_as!(Columns, "SELECT id, type_id, column_position, column_name, column_type, nullable, graphql_type FROM graph_registry_columns WHERE type_id = $1", col_id).fe...
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i64`, found `i32`
    |
    = note: this error originates in the macro `$crate::sqlx_macros::expand_query` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0308`.
error: could not compile `fuel-indexer-postgres` due to 4 previous errors
warning: build failed, waiting for other jobs to finish...
error: could not compile `fuel-indexer-postgres` due to 4 previous errors
    Building [======================>  ] 759/807: librocksdb-sys(build)                          
```

**Comment by ra0x3** [comment]
@tjsharp1 
- Best case scenario turned out to be the case. 
- Sqlx dev mentioned this is a known bug in the macro, fixed by casting types
- Just pushed a commit for that. Everything is working for me locally.
- I guess we can merge after conflict fixes 👌 

CC @JoshuaBatty

**Comment by JoshuaBatty** [comment]
Awesome nice work @ra0x3 !

Happy to give this a tick once the CI conflicts have been resolved.

**Review by JoshuaBatty — APPROVED** [review]
It's passing! Nice work. :shipit:

**Review by ra0x3 — APPROVED** [review]

**Pull request merged**
