### PR TITLE
enhancement: reimplement WasmArg Drop

### PR DESCRIPTION
**Pull request by lostman**
### Description

`Drop` for `WasmArg` was removed in #1072. It did not occur to me then to store `MutexGuard<'_, Store>` (instead of a full `Mutex`) in `WasmArg`.

Reimplementing `Drop` guarantees cleanup.

### Testing steps

CI testing.

### Changelog

* reimplement `Drop` for `WasmArg` to ensure cleanup.

### CODE REVIEW

**Comment by ra0x3** [comment]
@lostman 
- The description is a bit unclear as to what this PR is and does, could you add a bit more context?
- Also, given that these changes are a bit of a hot path, it would be nice to see the before/after result of this PR to confirm that the changes work as expected

**Comment by lostman** [comment]
@ra0x3, in #1072, I removed `Drop` implementation for `WasmArg` because at the time I did not see how do to it with the changes required for `wasmer` update.

So, the cleanup (dealloc) had to be done manually, and I put it here:
https://github.com/FuelLabs/fuel-indexer/pull/1245/files#diff-fa722c66d2896c684e5a26aa2c56b7ec1734888609fbb64ecbc7dfd6a420c4ffL849

However, this isn't the right place for it.

The call to WASM is here:
https://github.com/FuelLabs/fuel-indexer/pull/1245/files#diff-fa722c66d2896c684e5a26aa2c56b7ec1734888609fbb64ecbc7dfd6a420c4ffL830

And before the cleanup (dealloc), there is a possibility of the function returning with an error:
https://github.com/FuelLabs/fuel-indexer/pull/1245/files#diff-fa722c66d2896c684e5a26aa2c56b7ec1734888609fbb64ecbc7dfd6a420c4ffL835

Thus, cleanup wouldn't happen.

After I spotted the mistake, I opened a PR to fix it. And I have also realized that I could implement `Drop` after all.

This PR does that.

So,

1. a bug is fixed when cleanup might be skipped
2. `Drop` is reimplemented to restore the guarantee that cleanup always happens.

**Comment by deekerno** [comment]
@lostman: If you don't mind, I'd like to do some memory profiling on my side before approving this. I imagine that this probably would probably lead to more reasonable memory allocation over time and may have been a contributing factor to our memory issues that we saw a few days ago.

**Comment by lostman** [comment]
@deekerno, I don't mind. I recommend merging it sooner rather than later because it fixes a bug.

The type of errors that would trigger this is rare (e.g., WASM trap), so it shouldn't significantly contribute to the memory issues we've seen.

Running out of metering points would trigger it too, but with our generous default allocation, it shouldn't be happening either.

Still, if you find that it did contribute, please let me know 🙏

**Review by deekerno — APPROVED** [review]
Decided to do my memory profiling at a later time as it's not necessary to block this bug fix when I can just check out the commits on my own. 👌🏽

**Pull request merged**
