### PR TITLE
chore: update docs to beta-3

### LINKED ISSUE #590: Replace all `beta-2` doc references with `beta-3`
- Where possible, we recommend users connect to Fuel's `beta-2` test network
- Now that `beta-3` is out, we should update our docs to reference `beta-3`

### PR DESCRIPTION
**Pull request by rvmelkonian**
Closes #590 

Updates the docs to reference `beta-3` instead of `beta-2`.
Updates mention of `index` to `indexer` where appropriate.

### CODE REVIEW

**Comment by ra0x3** [comment]
@rvmelkonian 
- Docs look ok
- Did you by chance test to see if these things still work on beta-3?

**Comment by rvmelkonian** [comment]
I haven't tested. I will do now.

**Review by deekerno — COMMENTED** [review]
Is the `beta-3` address up yet? It doesn't seem to be; can't connect the indexer to it and there's no GraphQL playground up for it yet like there has been for beta-2 (https://node-beta-2.fuel.network/playground).

**Comment by ra0x3** [comment]
@deekerno 
- Yea that's why I wanted to test this out first.
- beta-4 is due on March 15th so my thinking was that beta-3 is currently up right now
- I'll ask someone

**Comment by rvmelkonian** [comment]
I'll close this now as it's stale. Can re open if we need it.

**Comment by ra0x3** [comment]
@rvmelkonian  Looks good. Will ✅ once conflicts are resolved

**Review by deekerno — APPROVED** [review]

**Review by ra0x3 — APPROVED** [review]

**Pull request merged**
