### PR TITLE
v0.25.0

### PR DESCRIPTION
**Pull request by deekerno**
This PR upgrades the Fuel indexer to be compatible with beta-5.

### CODE REVIEW

**Review by ra0x3 — DISMISSED** [review]
@deekerno approved keeping in mind this release is untested pending a beta5 endpoint

**Comment by deekerno** [comment]
This should be merged after #1523.

**Review by ra0x3 — APPROVED** [review]

**Comment by ra0x3** [comment]
Merging even though we haven't run the QA script 🤞🏼

**Comment by deekerno** [comment]
I'll mark the release as a release candidate, just so people are aware. 👌🏽

**Pull request merged**
