### PR TITLE
Book: Fix image, move text related to building book into external README

### PR DESCRIPTION
**Pull request by mitchmindtree**
It looks like we can't link to local items in the book that are outside
of the `src` directory. I've moved the `img` directory under `src` to
amend this.

The intro page previously contained a "Documentation" section which
explains how to build the mdbook. These steps aren't relevant to readers
of `fuel-indexer` who are just trying to familiarise with `fuel-indexer`
itself. I've moved this text into a README in the book's root directory,
just like we have for the Sway book's directory [here][1].

Also removes the line that recommends reading the book, as the reader is
already reading the book.

[1]: https://github.com/FuelLabs/sway/blob/master/docs/README.md

### CODE REVIEW

**Comment by mitchmindtree** [comment]
The CI error here seems unrelated. @tjsharp1 any ideas on what might be going on here?

I'm running up against this in #31 too.

**Review by ra0x3 — APPROVED** [review]
🚢 ✅ 👍

**Comment by adlerjohn** [comment]
Converting to draft until unblocked

**Comment by mitchmindtree** [comment]
Rebased onto master and the recent CI update - should be good to go now.

**Review by JoshuaBatty — APPROVED** [review]

**Review by ra0x3 — APPROVED** [review]

**Review by adlerjohn — APPROVED** [review]

**Pull request merged**
