### PR TITLE
enhancement: support introspection

### LINKED ISSUE #790: Support introspection queries on GraphQL endpoint
- This is a feature request from @luizstacio 
- Our GraphQL endpoint currently supports translating GraphQL queries to SQL queries
- However, that is not all this endpoint should do
- The endpoint should also determine whether or not the given request is for an "introspection" query
- If the request is for an "introspection" query, the endpoint should _not_ try to translate that to SQL
  - The endpoint should just parse the GraphQL schema, and return the introspection data
- This helps the FE team productivity by auto-completing queries and types, generating docs, and generating schema as well

Additional context
- Currently the `fuel-core` playground supports this
- If you open the fuel-core playground http://beta-3.fuel.network/playground and start typing a query, you can see the result of the introspection query
- Example output:
[sample-introspection-query.txt](https://github.com/FuelLabs/fuel-indexer/files/11312486/sample-introspection-query.txt)

### PR DESCRIPTION
**Pull request by rvmelkonian**
Closes #790 

See the issue for full context, it's all there 👌 

## Changelog 
• Add `introspect` method on `Schema` struct.
• Updates `query_graph` handler function to check for introspection and return that if requested. 
• Updates documentation.

## Testing
1. `cargo run --bin fuel-indexer -- run --manifest packages/fuel-indexer-tests/components/indices/fuel-indexer-test/fuel_indexer_test.yaml `
2. In your browser, go to `http://localhost:29987/api/playground/fuel_indexer_test/index1`
3. Send the query below 
(For extra testing you can test normal queries and other indexers, I did this, but if you're in a QA type of mood... )
```graphql
query IntrospectionQuery {
  __schema {
    types {
      name
      fields {
        name
        type {
          name
          kind
        }
      }
    }
  }
}
```
You should get the response
```json
{
  "data": {
    "__schema": {
      "mutationType": null,
      "queryType": {
        "name": "Query"
      },
      "subscriptionType": null,
      "types": [
        {
          "fields": [
            {
              "name": "QueryRoot",
              "type": {
                "kind": "NON_NULL",
                "ofType": {
                  "kind": "OBJECT",
                  "name": "QueryRoot"
                }
              }
            }
          ],
          "kind": "OBJECT",
          "name": "Query"
        },
        {
          "fields": [
            {
              "name": "gas_used",
              "type": {
                "kind": "NON_NULL",
                "ofType": {
                  "kind": "SCALAR",
                  "name": "UInt8!"
                }
              }
            },
            {
              "name": "id",
              "type": {
                "kind": "NON_NULL",
                "ofType": {
                  "kind": "SCALAR",
                  "name": "ID!"
                }
              }
            },
            {
              "name": "blob",
              "type": {
                "kind": "NON_NULL",
                "ofType": {
                  "kind": "SCALAR",
                  "name": "Blob!"
                }
              }
            },
            {
              "name": "result",
              "type": {
                "kind": "NON_NULL",
                "ofType": {
                  "kind": "SCALAR",
                  "name": "UInt8!"
                }
              }
            }
              ...
```

## Note
`mutationType` and `subscriptionType` fields have been set to null.

### CODE REVIEW

**Review by luizstacio — COMMENTED** [review]
Testing the PR locally here, I see the error

```txt
{
  "error": "Introspection result missing interfaces: { fields: [[Object]], kind: \"OBJECT\", name: \"Query\" }."
}
```

**Comment by rvmelkonian** [comment]
@luizstacio I forgot to mention in the PR description, that error shows on initial page load, but if you run the introspection query, it should work. Could you try that? Meanwhile I'll see if I can suppress that error on page load.

**Comment by ra0x3** [comment]
@rvmelkonian 
- Just an FYI doesn't seem to work for me either.
- When I open the playground I do see the error @luizstacio mentions
- When I click the "Schema" and the "Docs" tabs, I don't see anything -- I just see the loading spinner which never resolves

**Comment by rvmelkonian** [comment]
@ra0x3 I had a sync with @luizstacio late last night. The scope of this PR was just to do the introspection query and get the response back with the schema data (this is used for TS code gen). To get the schema and docs stuff to work in the playground, I would consider a separate PR as that involves editing JS and html from `async-graphql` crate. 

Did you try out the query in the description and get back a successful response?

**Comment by ra0x3** [comment]
@rvmelkonian Sounds good. I'll defer to @luizstacio for approval in terms of functionality working properly

**Comment by luizstacio** [comment]
> @rvmelkonian Sounds good. I'll defer to @luizstacio for approval in terms of functionality working properly

Docs and Schema tabs are loaded using the return of the introspect query, to be a valid return it should be loading this tabs also, this would give you the certainty that is working.

I was talk with @deekerno yesterday about investigate the possibility to use `async-graphql` [dynamic schemas](https://github.com/async-graphql/async-graphql#dynamic-schema). In order to replace the current GraphQL Parser. This should enable this features without the need to custom implementations, and also make sure that the response of GraphQL returns comply with GraphQL standard.

I'm mentioning this here, because if @deekerno is looking into it, this work may not be needed.

**Comment by ra0x3** [comment]
@deekerno Will defer to you with regard to @luizstacio 's comment [here](https://github.com/FuelLabs/fuel-indexer/pull/798#issuecomment-1523612069).

**Comment by rvmelkonian** [comment]
@ra0x3 @deekerno In that case I'll put this PR on hold then https://github.com/FuelLabs/fuel-indexer/pull/800 as I'm making heavy use of our current graphql parser. I'm all up for shifting to `async-graphql`, if we can get a compliant graphql endpoint out of the box that can support our needs, but I think this may require some rewrites elsewhere.

**Comment by deekerno** [comment]
It will definitely require some rewrites; I think it's just a question of how many and how much effort we're willing to put into it. It seems like it may be a net positive as far as type safety, but I'm still investigating prior art to see if we would lose any speed or start running into any sort of "N+1 problem" when it comes to queries. I'll update you all on Slack.

**Comment by rvmelkonian** [comment]
@luizstacio the logic for fetching the schema and docs is tucked away inside `async-graphql` crate. I'm only using that crate here to render out the playground, but everywhere else we are using our own `fuel-indexer-graphql-parser` package. This is why schema and docs do not load. But when you run the introspection query you should get all the data you need to be able to do TS gen. Let me know if this gives you what you need. 👌

**Comment by rvmelkonian** [comment]
Closing this as `async-graphql` provides the functionality and we will be switching to this shortly.

**Pull request closed without merging**
