### PR TITLE
fix: Fix TransferOut test

### LINKED ISSUE #1276: Investigate failing `TransferOut` receipt test
The `TransferOut` receipt test currently fails as the contract is unable to transfer the asset to an address. This should be fixed to ensure that our E2E test suite properly covers all receipts.

### PR DESCRIPTION
**Pull request by dadepo**
Closes #1276

### Description

Fixed the `TransferOut` receipt test 

### Changelog

The core of the change:

- Updated the contract to use `transfer_to_address`
- Updated the address the contract transfers too
- Appended append_variable_outputs when calling the contract methods

PS. The tests passes locally except for `commands::test_fuel_indexer_api_server_help_output` and `commands::test_fuel_indexer_api_server_run_help_output` but then they were also failing for me locally on develop branch.

### CODE REVIEW

**Comment by deekerno** [comment]
@dadepo Thanks for working on this, looks like everything works! Before approval, would you mind re-integrating the `TransferOut` test at the bottom of the `index_receipt_types` test? We had originally split it out to be able to ignore it, and now that you've fixed it, we can place it back where it belongs. 😄

**Comment by dadepo** [comment]
> @dadepo Thanks for working on this, looks like everything works! Before approval, would you mind re-integrating the `TransferOut` test at the bottom of the `index_receipt_types` test? We had originally split it out to be able to ignore it, and now that you've fixed it, we can place it back where it belongs. 😄

@deekerno Done!

**Review by deekerno — APPROVED** [review]
Everything works! 🎉

**Review by ra0x3 — APPROVED** [review]
Thanks @dadepo

**Pull request merged**
