### PR TITLE
chore: create Fuel node fixture

### PR DESCRIPTION
**Pull request by deekerno**
## Changelog
- Add node fixture to `fuel-indexer-tests`
- Adjust tests to spin up and tear down node fixture for each test
- Remove `fuel-node` package from workspace
- Remove `fuel-node` build step from CI
- Add binary using test node fixture to deploy contract for `hello-world` example

## Testing Steps
CI should pass with new Fuel node fixture. Additionally, the "Hello World" example has been adjusted; run through both the example README and the example in the documentation, and verify that everything works.

## Notes
- No big improvement in CI runtime; however, it does allow for all of our testing to be done through `cargo` actions and for us not to use extra scripts.
- A number of tests needed to be adjusted to either remove asserts that weren't properly testing values or to delete records from tables at test invocation to ensure a clean slate.

### CODE REVIEW

**Review by ra0x3 — CHANGES_REQUESTED** [review]
@deekerno 
- I don't think this was tested?
- After a bit of inspection, you can see that the `hello-world-test-node` binary is expecting a `CARGO_MANIFEST_DIR` but you're not providing one so the service exits.

```text
hello-world-postgres-1               | 2023-02-13 22:16:53.057 UTC [29] LOG:  database system was shut down at 2023-02-13 22:16:52 UTC
hello-world-postgres-1               | 2023-02-13 22:16:53.062 UTC [1] LOG:  database system is ready to accept connections
hello-world-hello-world-test-node-1  | Error: NotPresent
hello-world-hello-world-test-node-1 exited with code 1
hello-world-fuel-indexer-1           | Feb 13 22:16:55.749  INFO fuel_indexer: Configuration: IndexerConfig { fuel_node: FuelNodeConfig { host: "hello-world-test-node", port: "4000" }, graphql_api: GraphQLConfig { host: "0.0.0.0", port: "29987", run_migrations: true }, database: PostgresConfig { user: "postgres", password: "XXXX", host: "postgres", port: "5432", database: "postgres" }, metrics: true, stop_idle_indexers: false }
hello-world-fuel-indexer-1           | Feb 13 22:16:55.767  INFO sqlx::query: SELECT current_database(); rows affected: 0, rows returned: 1, elapsed: 1.059ms
hello-world-fuel-indexer-1           | Feb 13 22:16:55.769  INFO sqlx::query: SELECT pg_advisory_lock($1); rows affected: 1, rows returned: 1, elapsed: 1.259ms
hello-world-fuel-indexer-1           | Feb 13 22:16:55.777  INFO sqlx::query: CREATE TABLE IF NOT …; rows affected: 0, rows returned: 0, elapsed: 7.808ms
hello-world-fuel-indexer-1           |
hello-world-fuel-indexer-1           | CREATE TABLE IF NOT EXISTS _sqlx_migrations (
hello-world-fuel-indexer-1           |   version BIGINT PRIMARY KEY,
hello-world-fuel-indexer-1           |   description TEXT NOT NULL,
hello-world-fuel-indexer-1           |   installed_on TIMESTAMPTZ NOT NULL DEFAULT now(),
hello-world-fuel-indexer-1           |   success BOOLEAN NOT NULL,
```
- Also, `hello-world-test-node` is a mouthful lol. Maybe `hello-world-node`?

**Comment by deekerno** [comment]
That's what I get for trusting the find and replace. Let me quickly fix that.

And yeah, `hello-world-node` is better for sure. 👍🏽

**Comment by deekerno** [comment]
@ra0x3 It should be working now; however, I seem to be getting an error on deploying the index according to the instructions. The error is about foreign keys so I'm wondering if there was something off about my setup. Do you mind trying it and seeing if it works properly for you?

**Review by ra0x3 — CHANGES_REQUESTED** [review]
@deekerno 
- I seem to be unable to connect to the fuel node in the compose?

Output:
```text
ed: 331.889µs
hello-world-fuel-indexer-1      | Feb 14 14:47:33.620  INFO sqlx::query: COMMIT; rows affected: 0, rows returned: 0, elapsed: 414.460µs
hello-world-fuel-indexer-1      | Feb 14 14:47:33.620  INFO fuel_indexer::executor: No new blocks to process, sleeping.
hello-world-fuel-indexer-1      | Feb 14 14:47:34.627 ERROR fuel_indexer::executor: Failed to retrieve blocks: Error making HTTP request: error sending request for url (http://0.0.0.0:4000/graphql): error trying to connect: tcp connect error: Connection refused (os error 111)
hello-world-fuel-indexer-1      | Feb 14 14:47:34.628  INFO sqlx::query: BEGIN; rows affected: 0, rows returned: 0, elapsed: 379.737µs
hello-world-fuel-indexer-1      | Feb 14 14:47:34.629  INFO sqlx::query: COMMIT; rows affected: 0, rows returned: 0, elapsed: 266.823µs
hello-world-fuel-indexer-1      | Feb 14 14:47:34.629  INFO fuel_indexer::executor: No new blocks to process, sleeping.
hello-world-fuel-indexer-1      | Feb 14 14:47:35.635 ERROR fuel_indexer::executor: Failed to retrieve blocks: Error making HTTP request: error sending request for url (http://0.0.0.0:4000/graphql): error trying to connect: tcp connect error: Connection refused (os error 111)
```
- Testing steps
  - [ ] `git fetch && git checkout origin/deekerno/create-fuel-node-fixture`
  - [ ] `cd examples/hello-world`
  - [ ] `docker compose up --force-recreate`

**Comment by deekerno** [comment]
@ra0x3 Alright, it definitely works now. Clean out all old containers and volumes related to this, then run `docker compose up`, and then deploy using the command in the example README.

**Comment by deekerno** [comment]
Closing this up as most of the changes have been integrated in other PRs. 👍🏽

**Pull request closed without merging**
