### PR TITLE
Replace blocking `reqwest` usage with async

### PR DESCRIPTION
**Pull request by AlicanC**
Reposting https://github.com/FuelLabs/fuel-indexer/pull/1148 because it was merged too early and had to be reverted.

---

For some reason the `forc-index deploy` command began to blow up on my machine. It seems like [`reqwest::blocking` was never supposed to play well with `tokio`](https://github.com/seanmonstar/reqwest/issues/1233) but somehow it did until now?

Anyways, this PR eliminates any usage of `reqwest::blocking` so this shouldn't be a problem anymore.

### Testing steps

- Try the affected commands: `auth`, `deploy`, `remove` and `welcome`

### Changelog

- fix: certain `forc-index` commands crashing `tokio`

### CODE REVIEW

**Comment by ra0x3** [comment]
Waiting to see if this solves @LuizAsFight's issue in https://github.com/FuelLabs/fuel-indexer/issues/1070

**Review by deekerno — COMMENTED** [review]
Everything looks generally good. I'd like to see if this change alleviates @LuizAsFight's issue before approval.

Also, I know it hasn't been done much in this area, but can you add doc comments to any of the functions that you've adjusted? We may as well start documenting this crate while we're changing things.

**Comment by LuizAsFight** [comment]
> Everything looks generally good. I'd like to see if this change alleviates @LuizAsFight's issue before approval.
> 
> Also, I know it hasn't been done much in this area, but can you add doc comments to any of the functions that you've adjusted? We may as well start documenting this crate while we're changing things.

yes it worked 👏🏻

**Review by ra0x3 — APPROVED** [review]
Thanks @AlicanC 🙏🏽

**Pull request merged**
