### PR TITLE
Swap structopt for clap

### PR DESCRIPTION
**Pull request by ra0x3**
### Description
- This PR swaps the use of `structopt` for `clap`

### Testing steps
- Starting a service via CLI opts should work as expected

### CODE REVIEW

**Comment by JoshuaBatty** [comment]
Looks like structopt is still being using in api_server. Happy to approve once that has also been changed to use clap.

**Comment by mitchmindtree** [comment]
Also @ra0x3, don't forget to change the PR mode to "Ready for review" otherwise I think reviewers might not get notifications.

**Comment by ra0x3** [comment]
@JoshuaBatty 
- Hm, this PR is based off of the Docker PR - so I'd have to update that PR, then pull the changes into this. 
- Since this PR isn't broken could we merge this as-is, and I file an issue to update the API server? 
  - Not sure how I forgot this api_server crate 🤦

**Comment by ra0x3** [comment]
@JoshuaBatty @mitchmindtree Changes made here. This is ready for review, but won't be merged until after #116

**Comment by ra0x3** [comment]
@JoshuaBatty @mitchmindtree Sorry for the spam, this one should be ready to go now 👍

**Review by mitchmindtree — APPROVED** [review]
:ok_hand:

**Pull request merged**
