### PR TITLE
doc: Improve --replace-indexer message when redeploying an indexer

### LINKED ISSUE #1461: Improve `--replace-indexer` message when redeploying an indexer
I had a service running in the docker container which did not include the `--replace-indexer` flag.

When I have altered an indexer and wanted to redeploy it I was presented with a message telling me to add the `--replace-indexer` flag but it did not tell me where to use it.

I have assumed that I was meant to replace

```bash
forc index deploy
```

with

```bash
forc index deploy --replace-indexer
```

but that was insufficient.

To fix the issue and redeploy the new version of the indexer I had to start the indexer service with that `--replace--indexer` flag in order for the flag in the `deploy` command to work.

Solution: replace the current message to inform the user that both the service and the deploy command must provide the `--replace-indexer` flag in order to redeploy an indexer under the same name.

### PR DESCRIPTION
**Pull request by richardgreg**
close #1461

Thanks for opening a PR with the Fuel Indexer project. Please review the **Checklist** below and ensure you've completed all of the necessary steps to make this PR review as painless as possible.

### Checklist
- [x] Ensure your top-level commit message is in line with our [contributor guidelines](./CONTRIBUTING.md).
- [x] Please add proper labels.
- [ ] If there is an issue associated with this PR, please link the issue (right-hand sidebar)
- [ ] If there is not an issue associated with this PR, add this PR to the "Fuel Indexer" project (right-hand sidebar)
- [ ] Please allow Codeowners at least 24 hours to do a first-pass review.
- [ ] Please add thoroughly detailed testing steps below.
- [ ] Please keep your Changelog message short and sweet.

### Description

Please include a short description of what this PR does.

### Testing steps

Please provide the _exact_ testing steps for the reviewer(s) if this PR requires testing.

### Changelog

Please add neat Changelog info here, according to our [Contributor's Guide](./CONTRIBUTING.md).

### CODE REVIEW

**Review by deekerno — CHANGES_REQUESTED** [review]
Hey @richardgreg, thanks for opening a PR for this issue!

However, it doesn't fix what @Braqzen had mentioned:
> To fix the issue and redeploy the new version of the indexer I had to start the indexer service with that --replace--indexer flag in order for the flag in the deploy command to work.
>
>Solution: replace the current message to inform the user that both the service and the deploy command must provide the --replace-indexer flag in order to redeploy an indexer under the same name.

In this case, I would do two things. First, I would change your text to state that the indexer already exists, but replacing an indexer is not enabled; the user should restart the service with the `--replace-indexer` flag to enable the functionality. After that, I would adjust the message in `forc index deploy` to make it more clear that the indexer service does not have indexer replacement enabled.

**Comment by richardgreg** [comment]
I get it. I was originally working on it based on intuition and didn't read the docs. 😓 

I'll push a fix ASAP

**Comment by richardgreg** [comment]
Also @deekerno, some clarification on the instruction before I push an update. 😊

If a user enters `forc index deploy --replace-index` in a situation whereby `--replace-index` was not stated when the service was ran, the error message should read: `Failed to replace indexer: Indexer({namespace}.{identifier}) exists but replacing the indexer was not enabled. Restart the indexer service with --replace-indexer to enable the functionality.`

If a user enters `forc index deploy` in a situation whereby `--replace-index` was not stated when the service was ran, the error message should read: `Indexer({namespace}.{identifier}) already exists and replacing an indexer is not enabled. Use --replace-indexer to restart the indexer service and again during deployment.`

**Comment by richardgreg** [comment]
Hi @deekerno, I'm not one to abandon work so I'm curious why the PR was closed without resolution 🙂. I hadn't pushed an update because you never okayed my suggestion. If you have an ideal text replacement in mind, paste it and I'll update it.

**Comment by deekerno** [comment]
@richardgreg I've closed all open PRs on this repository as we're starting work on a new implementation of the Fuel indexer. The closure of this PR was purely because of the team's decision to focus all of our energy on the new implementation, and not because of any deficiency on the part of your contribution. As we build out the next iteration (the code for which can be found [here](https://github.com/FuelLabs/fuels-indexer)), please feel free to make contributions if you like.

**Pull request closed without merging**
