### PR TITLE
fix: add fuel-core-lib feature to binary

### PR DESCRIPTION
**Pull request by ra0x3**
### Description
- This PR adds back the `fuel-core-lib` to the `fuel-indexer` and `fuel-indexer-api-server` binaries

### Testing steps
- [ ] Docker should work
  - `docker build -t fuel-indexer/local:latest -f deployment/Dockerfile .`
  - `docker run $IMAGE ./fuel-indexer run --run-migrations --local-fuel-node`
- [ ] Build local indexer `cargo build -p fuel-indexer --features fuel-core-lib`
- [ ] Start service and start fuel node `./target/release/fuel-indexer run --local-fuel-node --run-migrations`

### Changelog
- fix: add fuel-core-lib feature to binary

### CODE REVIEW

**Review by deekerno — APPROVED** [review]
Testing steps work as described. 👍🏽

**Comment by ra0x3** [comment]
@rvmelkonian Does `docker run $IMAGE ./fuel-indexer run --help` show the `--local-fuel-node` option? If not, you might have cached build or something 🤔

**Comment by rvmelkonian** [comment]
I had actually cleared out all my images recently. Pretty sure this was a fresh build. I also get the same error when running
`/target/release/fuel-indexer run --local-fuel-node --run-migrations`.
After building the indexer. Let me try `cargo clean`

**Comment by deekerno** [comment]
The build command in the testing steps compiles to `./target/debug/fuel-indexer` rather than `./target/release/fuel-indexer`.

**Pull request merged**
