### PR TITLE
Refactor CI into concurrent jobs. Add mdbook and udeps checks.

### PR DESCRIPTION
**Pull request by mitchmindtree**
Also adds `--locked` to several cargo jobs to ensure that the `Cargo.lock` file is valid.

### CODE REVIEW

**Comment by mitchmindtree** [comment]
OK, looks like running these jobs concurrently cuts the overall CI duration from ~25 mins down to around ~15 mins. Still really long, but better!

I've removed the `cargo udeps` check in favour of a future PR that checks packages more granularly as there were some false positives in there. #62.

We'll also want to test the `--all-features` set, but there were some issues with this so I've opened #63.

**Review by ra0x3 — DISMISSED** [review]
- Looks good as is
- https://github.com/FuelLabs/fuel-indexer/issues/64 can be handled in a follow up (if not this PR)

**Comment by mitchmindtree** [comment]
Sorry @ra0x3, just noticed the `publish` job is behaving a little strangely (triggered when it shouldn't have, but failed anyway) and I've tried properly forwarding on the success state in the `validation-complete` job. Will re-ping once ready again :)

**Comment by mitchmindtree** [comment]
OK, fixed the odd `publish` behaviour, I think this is good to go.

@adlerjohn could you change the "Required" job from the old `build` job to the new `validation-complete` one?

**Pull request merged**
